
local Passivity_Skill = {
	["SK001"] = {	
		["name"] = "skill_B001",
		["desc"] = "SK001_text",
		["lower_level"] = "skill_B001_lower",
		["skill_upgrade"] = "SK001_upgrade",
		["icon"] = "skill_B001.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0.002,
		["DEF"] = 0,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0.002,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0.002,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0.002,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "蛮力",
	},
	["SK002"] = {	
		["name"] = "skill_B002",
		["desc"] = "SK002_text",
		["lower_level"] = "skill_B002_lower",
		["skill_upgrade"] = "SK002_upgrade",
		["icon"] = "skill_B010.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0.002,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0.002,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0.002,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0.002,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "强心",
	},
	["SK003"] = {	
		["name"] = "skill_B003",
		["desc"] = "SK003_text",
		["lower_level"] = "skill_B003_lower",
		["skill_upgrade"] = "SK003_upgrade",
		["icon"] = "skill_B005.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0.002,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0.002,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0.002,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0.002,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "兽痕",
	},
	["SK004"] = {	
		["name"] = "skill_B004",
		["desc"] = "SK004_text",
		["lower_level"] = "skill_B004_lower",
		["skill_upgrade"] = "SK004_upgrade",
		["icon"] = "skill_B008.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0.002,
		["critRate"] = 0,
		["antiknockRate"] = 0.002,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0.002,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0.002,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "不服",
	},
	["SK005"] = {	
		["name"] = "skill_B005",
		["desc"] = "SK005_text",
		["lower_level"] = "skill_B005_lower",
		["skill_upgrade"] = "SK005_upgrade",
		["icon"] = "skill_B009.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0.002,
		["DEF"] = 0,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0.002,
		["morale"] = 0,
		["ATN_GROW"] = 0.002,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0.002,
		["morale_GROW"] = 0,
		["passivity_skill"] = "勇毅",
	},
	["SK006"] = {	
		["name"] = "skill_B006",
		["desc"] = "SK006_text",
		["lower_level"] = "skill_B006_lower",
		["skill_upgrade"] = "SK006_upgrade",
		["icon"] = "skill_B008.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0.002,
		["INT"] = 0,
		["RES"] = 0.002,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0.002,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0.002,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0.002,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0.002,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "护佑",
	},
	["SK008"] = {	
		["name"] = "skill_B008",
		["desc"] = "SK008_text",
		["lower_level"] = "skill_B008_lower",
		["skill_upgrade"] = "SK008_upgrade",
		["icon"] = "skill_B025.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0.002,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0.002,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0.002,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0.002,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "灵甲",
	},
	["SK009"] = {	
		["name"] = "skill_B009",
		["desc"] = "SK009_text",
		["lower_level"] = "skill_B009_lower",
		["skill_upgrade"] = "SK009_upgrade",
		["icon"] = "skill_B019.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0.002,
		["DEF"] = 0.002,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0.002,
		["DEF_GROW"] = 0.002,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "强力",
	},
	["SK010"] = {	
		["name"] = "skill_B010",
		["desc"] = "SK010_text",
		["lower_level"] = "skill_B010_lower",
		["skill_upgrade"] = "SK010_upgrade",
		["icon"] = "ZJS_012.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0.002,
		["antiknockRate"] = 0,
		["wreckRate"] = 0.002,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0.002,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0.002,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "冲锋",
	},
	["SK011"] = {	
		["name"] = "skill_B011",
		["desc"] = "SK011_text",
		["lower_level"] = "skill_B011_lower",
		["skill_upgrade"] = "SK011_upgrade",
		["icon"] = "skill_B018.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0.002,
		["INT"] = 0,
		["RES"] = 0.002,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0.002,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0.002,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0.002,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0.002,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "金刚",
	},
	["SK012"] = {	
		["name"] = "skill_B012",
		["desc"] = "SK012_text",
		["lower_level"] = "skill_B012_lower",
		["skill_upgrade"] = "SK012_upgrade",
		["icon"] = "skill_B025.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0.002,
		["INT"] = 0.002,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0.002,
		["INT_GROW"] = 0.002,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "调和",
	},
	["SK013"] = {	
		["name"] = "skill_B013",
		["desc"] = "SK013_text",
		["lower_level"] = "skill_B013_lower",
		["skill_upgrade"] = "SK013_upgrade",
		["icon"] = "ZJS_005.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0.002,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0.002,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0.002,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0.002,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "劫火",
	},
	["SK014"] = {	
		["name"] = "skill_B014",
		["desc"] = "SK014_text",
		["lower_level"] = "skill_B014_lower",
		["skill_upgrade"] = "SK014_upgrade",
		["icon"] = "skill_66.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0.002,
		["RES"] = 0.002,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0.002,
		["RES_GROW"] = 0.002,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "智谋",
	},
	["SK015"] = {	
		["name"] = "skill_B015",
		["desc"] = "SK015_text",
		["lower_level"] = "skill_B015_lower",
		["skill_upgrade"] = "SK015_upgrade",
		["icon"] = "skill_62.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0.002,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0.002,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0.002,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0.002,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "刃甲",
	},
	["SK016"] = {	
		["name"] = "skill_B016",
		["desc"] = "SK016_text",
		["lower_level"] = "skill_B016_lower",
		["skill_upgrade"] = "SK016_upgrade",
		["icon"] = "skill_69.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0,
		["RES"] = 0.002,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0.002,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0.002,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0.002,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "灵逸",
	},
	["SK017"] = {	
		["name"] = "skill_B017",
		["desc"] = "SK017_text",
		["lower_level"] = "skill_B017_lower",
		["skill_upgrade"] = "SK017_upgrade",
		["icon"] = "skill_79.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0.002,
		["DEF"] = 0,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0.002,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "猛攻",
	},
	["SK018"] = {	
		["name"] = "skill_B018",
		["desc"] = "SK018_text",
		["lower_level"] = "skill_B018_lower",
		["skill_upgrade"] = "SK018_upgrade",
		["icon"] = "ZJS_025.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0.002,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0.002,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "智慧",
	},
	["SK019"] = {	
		["name"] = "skill_B019",
		["desc"] = "SK019_text",
		["lower_level"] = "skill_B019_lower",
		["skill_upgrade"] = "SK019_upgrade",
		["icon"] = "ZJS_008.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0.002,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0.002,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "体魄",
	},
	["SK020"] = {	
		["name"] = "skill_B020",
		["desc"] = "SK020_text",
		["lower_level"] = "skill_B020_lower",
		["skill_upgrade"] = "SK020_upgrade",
		["icon"] = "skill_14.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0.002,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0.002,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "命中",
	},
	["SK021"] = {	
		["name"] = "skill_B021",
		["desc"] = "SK021_text",
		["lower_level"] = "skill_B021_lower",
		["skill_upgrade"] = "SK021_upgrade",
		["icon"] = "ZJS_015.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0.002,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0.002,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "闪避",
	},
	["SK022"] = {	
		["name"] = "skill_B022",
		["desc"] = "SK022_text",
		["lower_level"] = "skill_B022_lower",
		["skill_upgrade"] = "SK022_upgrade",
		["icon"] = "ZJS_009.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0.002,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0.002,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "暴击",
	},
	["SK023"] = {	
		["name"] = "skill_B023",
		["desc"] = "SK023_text",
		["lower_level"] = "skill_B023_lower",
		["skill_upgrade"] = "SK023_upgrade",
		["icon"] = "ZJS_019.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0.002,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0.002,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "抗暴",
	},
	["SK024"] = {	
		["name"] = "skill_B024",
		["desc"] = "SK024_text",
		["lower_level"] = "skill_B024_lower",
		["skill_upgrade"] = "SK024_upgrade",
		["icon"] = "skill_B009.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0.002,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0.002,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "破击",
	},
	["SK025"] = {	
		["name"] = "skill_B025",
		["desc"] = "SK025_text",
		["lower_level"] = "skill_B025_lower",
		["skill_upgrade"] = "SK025_upgrade",
		["icon"] = "ZJS_020.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0.002,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0.002,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "反伤",
	},
	["SK026"] = {	
		["name"] = "skill_B026",
		["desc"] = "SK026_text",
		["lower_level"] = "skill_B026_lower",
		["skill_upgrade"] = "SK026_upgrade",
		["icon"] = "skill_B014.png",
		["basis"] = 0,
		["grown"] = 0.001,
		["param"] = {
			{
				["original"] = 0.1,
				["growth"] = 0.1,
			},
			{
				["original"] = 0.1,
				["growth"] = 0.1,
			},
		},
		["ATN"] = 0.001,
		["DEF"] = 0,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0.001,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0.001,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0.001,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "强壮",
	},
	["SK027"] = {	
		["name"] = "skill_B027",
		["desc"] = "SK027_text",
		["lower_level"] = "skill_B027_lower",
		["skill_upgrade"] = "SK027_upgrade",
		["icon"] = "skill_60.png",
		["basis"] = 0,
		["grown"] = 0.001,
		["param"] = {
			{
				["original"] = 0.1,
				["growth"] = 0.1,
			},
			{
				["original"] = 0.1,
				["growth"] = 0.1,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0.001,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0.001,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0.001,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0.001,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "冥想",
	},
	["SK028"] = {	
		["name"] = "skill_B028",
		["desc"] = "SK028_text",
		["lower_level"] = "skill_B028_lower",
		["skill_upgrade"] = "SK028_upgrade",
		["icon"] = "heroskill_11.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0.002,
		["INT"] = 0,
		["RES"] = 0.002,
		["SPD"] = 0,
		["HP"] = 0.002,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0.002,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0.002,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0.002,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "神盾",
	},
	["SK029"] = {	
		["name"] = "skill_B029",
		["desc"] = "SK029_text",
		["lower_level"] = "skill_B029_lower",
		["skill_upgrade"] = "SK029_upgrade",
		["icon"] = "skill_80.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0.002,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0.002,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0.002,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0.002,
		["morale_GROW"] = 0,
		["passivity_skill"] = "统御",
	},
	["SK030"] = {	
		["name"] = "skill_B030",
		["desc"] = "SK030_text",
		["lower_level"] = "skill_B030_lower",
		["skill_upgrade"] = "SK030_upgrade",
		["icon"] = "skill_B003.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0.002,
		["DEF"] = 0,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0.002,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0.002,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0.002,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "血殇",
	},
	["SK031"] = {	
		["name"] = "skill_B031",
		["desc"] = "SK031_text",
		["lower_level"] = "skill_B031_lower",
		["skill_upgrade"] = "SK031_upgrade",
		["icon"] = "skill_66.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
			{
				["original"] = 0.2,
				["growth"] = 0.2,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0.002,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0.002,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0.002,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0.002,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "鬼谋",
	},
	["SK032"] = {	
		["name"] = "skill_B032",
		["desc"] = "SK032_text",
		["lower_level"] = "skill_B032_lower",
		["skill_upgrade"] = "SK032_upgrade",
		["icon"] = "ZJS_012.png",
		["basis"] = 0,
		["grown"] = 0.003,
		["param"] = {
			{
				["original"] = 0.3,
				["growth"] = 0.3,
			},
			{
				["original"] = 0.3,
				["growth"] = 0.3,
			},
		},
		["ATN"] = 0.003,
		["DEF"] = 0,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0.003,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "军威",
	},
	["SK033"] = {	
		["name"] = "skill_B033",
		["desc"] = "SK033_text",
		["lower_level"] = "skill_B033_lower",
		["skill_upgrade"] = "SK033_upgrade",
		["icon"] = "skill_B024.png",
		["basis"] = 0,
		["grown"] = 0.003,
		["param"] = {
			{
				["original"] = 0.3,
				["growth"] = 0.3,
			},
			{
				["original"] = 0.3,
				["growth"] = 0.3,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0.003,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0.003,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "无双",
	},
	["SK034"] = {	
		["name"] = "skill_B034",
		["desc"] = "SK034_text",
		["lower_level"] = "skill_B034_lower",
		["skill_upgrade"] = "SK034_upgrade",
		["icon"] = "skill_10.png",
		["basis"] = 0,
		["grown"] = 0.0015,
		["param"] = {
			{
				["original"] = 0.15,
				["growth"] = 0.15,
			},
			{
				["original"] = 0.15,
				["growth"] = 0.15,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0.0015,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0.0015,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0.0015,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0.0015,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "皇冕",
	},
	["SK035"] = {	
		["name"] = "skill_B035",
		["desc"] = "SK035_text",
		["lower_level"] = "skill_B035_lower",
		["skill_upgrade"] = "SK035_upgrade",
		["icon"] = "skill_20.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.1,
				["growth"] = 0.1,
			},
			{
				["original"] = 0.1,
				["growth"] = 0.1,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0,
		["antiknockRate"] = 0.002,
		["wreckRate"] = 0,
		["blockRate"] = 0.002,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0.002,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0.002,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "固守",
	},
	["SK036"] = {	
		["name"] = "skill_B036",
		["desc"] = "SK036_text",
		["lower_level"] = "skill_B036_lower",
		["skill_upgrade"] = "SK036_upgrade",
		["icon"] = "skill_31.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.1,
				["growth"] = 0.1,
			},
			{
				["original"] = 0.1,
				["growth"] = 0.1,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0,
		["critRate"] = 0.002,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0,
		["critRate_GROW"] = 0.002,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "锋芒",
	},
	["SK037"] = {	
		["name"] = "skill_B037",
		["desc"] = "SK037_text",
		["lower_level"] = "skill_B037_lower",
		["skill_upgrade"] = "SK037_upgrade",
		["icon"] = "ZJS_015.png",
		["basis"] = 0,
		["grown"] = 0.002,
		["param"] = {
			{
				["original"] = 0.1,
				["growth"] = 0.1,
			},
			{
				["original"] = 0.1,
				["growth"] = 0.1,
			},
		},
		["ATN"] = 0,
		["DEF"] = 0,
		["INT"] = 0,
		["RES"] = 0,
		["SPD"] = 0,
		["HP"] = 0,
		["counterattack"] = 0,
		["hitRate"] = 0,
		["dodgeRate"] = 0.002,
		["critRate"] = 0,
		["antiknockRate"] = 0,
		["wreckRate"] = 0,
		["blockRate"] = 0,
		["hurtRate"] = 0,
		["avoidHurtRate"] = 0,
		["morale"] = 0,
		["ATN_GROW"] = 0,
		["DEF_GROW"] = 0,
		["INT_GROW"] = 0,
		["RES_GROW"] = 0,
		["SPD_GROW"] = 0,
		["HP_GROW"] = 0,
		["hitRate_GROW"] = 0,
		["dodgeRate_GROW"] = 0.002,
		["critRate_GROW"] = 0,
		["antiknockRate_GROW"] = 0,
		["wreckRate_GROW"] = 0,
		["blockRate_GROW"] = 0,
		["hurtRate_GROW"] = 0,
		["avoidHurtRate_GROW"] = 0,
		["morale_GROW"] = 0,
		["passivity_skill"] = "闪现",
	},
}

return Passivity_Skill