
local Charpter = {
	["C01"] = {	
		["name"] = "C01",
		["pev"] = "0",
		["sum"] = 8,
		["index"] = 1,
		["level"] = 1,
		["open_pic"] = "zhangjie_juqing_2.png",
		["open_music"] = "voice_pangbai_005.mp3",
		["location"] = 2,
		["desc"] = "CD01",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD01",
		["pic"] = "fuben_beijing_001.jpg",
		["pic3"] = "fuben_zhangjie_1.png",
	},
	["C02"] = {	
		["name"] = "C02",
		["pev"] = "C01",
		["sum"] = 8,
		["index"] = 2,
		["level"] = 5,
		["open_pic"] = "zhangjie_juqing_7.png",
		["open_music"] = "voice_pangbai_006.mp3",
		["location"] = 2,
		["desc"] = "CD02",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD02",
		["pic"] = "fuben_beijing_003.jpg",
		["pic3"] = "fuben_zhangjie_2.png",
	},
	["C03"] = {	
		["name"] = "C03",
		["pev"] = "C02",
		["sum"] = 10,
		["index"] = 3,
		["level"] = 10,
		["open_pic"] = "zhangjie_juqing_4.png",
		["open_music"] = "voice_pangbai_007.mp3",
		["location"] = 2,
		["desc"] = "CD03",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD03",
		["pic"] = "fuben_beijing_005.jpg",
		["pic3"] = "fuben_zhangjie_3.png",
	},
	["C04"] = {	
		["name"] = "C04",
		["pev"] = "C03",
		["sum"] = 10,
		["index"] = 4,
		["level"] = 15,
		["open_pic"] = "zhangjie_juqing_17.png",
		["open_music"] = "voice_pangbai_008.mp3",
		["location"] = 2,
		["desc"] = "CD04",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD04",
		["pic"] = "fuben_beijing_012.jpg",
		["pic3"] = "fuben_zhangjie_4.png",
	},
	["C05"] = {	
		["name"] = "C05",
		["pev"] = "C04",
		["sum"] = 10,
		["index"] = 5,
		["level"] = 20,
		["open_pic"] = "zhangjie_juqing_13.png",
		["open_music"] = "voice_pangbai_009.mp3",
		["location"] = 2,
		["desc"] = "CD05",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD05",
		["pic"] = "fuben_beijing_010.jpg",
		["pic3"] = "fuben_zhangjie_5.png",
	},
	["C06"] = {	
		["name"] = "C06",
		["pev"] = "C05",
		["sum"] = 10,
		["index"] = 6,
		["level"] = 25,
		["open_pic"] = "zhangjie_juqing_9.png",
		["open_music"] = "voice_pangbai_010.mp3",
		["location"] = 2,
		["desc"] = "CD06",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD06",
		["pic"] = "fuben_beijing_001.jpg",
		["pic3"] = "fuben_zhangjie_6.png",
	},
	["C07"] = {	
		["name"] = "C07",
		["pev"] = "C06",
		["sum"] = 10,
		["index"] = 7,
		["level"] = 30,
		["open_pic"] = "zhangjie_juqing_4.png",
		["open_music"] = "voice_pangbai_011.mp3",
		["location"] = 2,
		["desc"] = "CD07",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD07",
		["pic"] = "fuben_beijing_006.jpg",
		["pic3"] = "fuben_zhangjie_7.png",
	},
	["C08"] = {	
		["name"] = "C08",
		["pev"] = "C07",
		["sum"] = 10,
		["index"] = 8,
		["level"] = 35,
		["open_pic"] = "zhangjie_juqing_1.png",
		["open_music"] = "voice_pangbai_012.mp3",
		["location"] = 2,
		["desc"] = "CD08",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD08",
		["pic"] = "fuben_beijing_009.jpg",
		["pic3"] = "fuben_zhangjie_8.png",
	},
	["C09"] = {	
		["name"] = "C09",
		["pev"] = "C08",
		["sum"] = 10,
		["index"] = 9,
		["level"] = 40,
		["open_pic"] = "zhangjie_juqing_10.png",
		["open_music"] = "voice_pangbai_013.mp3",
		["location"] = 2,
		["desc"] = "CD09",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD09",
		["pic"] = "fuben_beijing_010.jpg",
		["pic3"] = "fuben_zhangjie_9.png",
	},
	["C10"] = {	
		["name"] = "C10",
		["pev"] = "C09",
		["sum"] = 10,
		["index"] = 10,
		["level"] = 45,
		["open_pic"] = "zhangjie_juqing_14.png",
		["open_music"] = "voice_pangbai_014.mp3",
		["location"] = 2,
		["desc"] = "CD10",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD10",
		["pic"] = "fuben_beijing_011.jpg",
		["pic3"] = "fuben_zhangjie_10.png",
	},
	["C11"] = {	
		["name"] = "C11",
		["pev"] = "C10",
		["sum"] = 10,
		["index"] = 11,
		["level"] = 50,
		["open_pic"] = "zhangjie_juqing_6.png",
		["open_music"] = "voice_pangbai_015.mp3",
		["location"] = 2,
		["desc"] = "CD11",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD11",
		["pic"] = "fuben_beijing_012.jpg",
		["pic3"] = "fuben_zhangjie_11.png",
	},
	["C12"] = {	
		["name"] = "C12",
		["pev"] = "C11",
		["sum"] = 10,
		["index"] = 12,
		["level"] = 55,
		["open_pic"] = "zhangjie_juqing_3.png",
		["open_music"] = "voice_pangbai_016.mp3",
		["location"] = 2,
		["desc"] = "CD12",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD12",
		["pic"] = "fuben_beijing_003.jpg",
		["pic3"] = "fuben_zhangjie_12.png",
	},
	["C13"] = {	
		["name"] = "C13",
		["pev"] = "C12",
		["sum"] = 10,
		["index"] = 13,
		["level"] = 60,
		["open_pic"] = "zhangjie_juqing_16.png",
		["open_music"] = "voice_pangbai_017.mp3",
		["location"] = 2,
		["desc"] = "CD13",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD13",
		["pic"] = "fuben_beijing_004.jpg",
		["pic3"] = "fuben_zhangjie_13.png",
	},
	["C14"] = {	
		["name"] = "C14",
		["pev"] = "C13",
		["sum"] = 10,
		["index"] = 14,
		["level"] = 65,
		["open_pic"] = "zhangjie_juqing_1.png",
		["open_music"] = "voice_pangbai_018.mp3",
		["location"] = 2,
		["desc"] = "CD14",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD14",
		["pic"] = "fuben_beijing_003.jpg",
		["pic3"] = "fuben_zhangjie_14.png",
	},
	["C15"] = {	
		["name"] = "C15",
		["pev"] = "C14",
		["sum"] = 10,
		["index"] = 15,
		["level"] = 70,
		["open_pic"] = "zhangjie_juqing_5.png",
		["open_music"] = "voice_pangbai_019.mp3",
		["location"] = 2,
		["desc"] = "CD15",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD15",
		["pic"] = "fuben_beijing_001.jpg",
		["pic3"] = "fuben_zhangjie_15.png",
	},
	["C16"] = {	
		["name"] = "C16",
		["pev"] = "C15",
		["sum"] = 10,
		["index"] = 16,
		["level"] = 75,
		["open_pic"] = "zhangjie_juqing_4.png",
		["open_music"] = "voice_pangbai_020.mp3",
		["location"] = 2,
		["desc"] = "CD16",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD16",
		["pic"] = "fuben_beijing_002.jpg",
		["pic3"] = "fuben_zhangjie_16.png",
	},
	["C17"] = {	
		["name"] = "C17",
		["pev"] = "C16",
		["sum"] = 10,
		["index"] = 17,
		["level"] = 80,
		["open_pic"] = "zhangjie_juqing_6.png",
		["open_music"] = "voice_pangbai_021.mp3",
		["location"] = 2,
		["desc"] = "CD17",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD17",
		["pic"] = "fuben_beijing_003.jpg",
		["pic3"] = "fuben_zhangjie_17.png",
	},
	["C18"] = {	
		["name"] = "C18",
		["pev"] = "C17",
		["sum"] = 10,
		["index"] = 18,
		["level"] = 85,
		["open_pic"] = "zhangjie_juqing_3.png",
		["open_music"] = "voice_pangbai_022.mp3",
		["location"] = 2,
		["desc"] = "CD18",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD18",
		["pic"] = "fuben_beijing_004.jpg",
		["pic3"] = "fuben_zhangjie_18.png",
	},
	["C19"] = {	
		["name"] = "C19",
		["pev"] = "C18",
		["sum"] = 10,
		["index"] = 19,
		["level"] = 90,
		["open_pic"] = "zhangjie_juqing_17.png",
		["open_music"] = "voice_pangbai_023.mp3",
		["location"] = 2,
		["desc"] = "CD19",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD19",
		["pic"] = "fuben_beijing_003.jpg",
		["pic3"] = "fuben_zhangjie_19.png",
	},
	["C20"] = {	
		["name"] = "C20",
		["pev"] = "C19",
		["sum"] = 10,
		["index"] = 20,
		["level"] = 95,
		["open_pic"] = "zhangjie_juqing_16.png",
		["open_music"] = "voice_pangbai_024.mp3",
		["location"] = 2,
		["desc"] = "CD20",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD20",
		["pic"] = "fuben_beijing_010.jpg",
		["pic3"] = "fuben_zhangjie_20.png",
	},
	["C21"] = {	
		["name"] = "C21",
		["pev"] = "C20",
		["sum"] = 10,
		["index"] = 21,
		["level"] = 100,
		["open_pic"] = "zhangjie_juqing_2.png",
		["open_music"] = "voice_pangbai_025.mp3",
		["location"] = 2,
		["desc"] = "CD21",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD21",
		["pic"] = "fuben_beijing_009.jpg",
		["pic3"] = "fuben_zhangjie_21.png",
	},
	["C22"] = {	
		["name"] = "C22",
		["pev"] = "C21",
		["sum"] = 10,
		["index"] = 22,
		["level"] = 105,
		["open_pic"] = "zhangjie_juqing_1.png",
		["open_music"] = "voice_pangbai_026.mp3",
		["location"] = 2,
		["desc"] = "CD22",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD22",
		["pic"] = "fuben_beijing_006.jpg",
		["pic3"] = "fuben_zhangjie_22.png",
	},
	["C23"] = {	
		["name"] = "C23",
		["pev"] = "C22",
		["sum"] = 10,
		["index"] = 23,
		["level"] = 110,
		["open_pic"] = "zhangjie_juqing_4.png",
		["open_music"] = "voice_pangbai_027.mp3",
		["location"] = 2,
		["desc"] = "CD23",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD23",
		["pic"] = "fuben_beijing_001.jpg",
		["pic3"] = "fuben_zhangjie_23.png",
	},
	["C24"] = {	
		["name"] = "C24",
		["pev"] = "C23",
		["sum"] = 10,
		["index"] = 24,
		["level"] = 115,
		["open_pic"] = "zhangjie_juqing_11.png",
		["open_music"] = "voice_pangbai_028.mp3",
		["location"] = 2,
		["desc"] = "CD24",
		["fristReward1"] = {
			{
				["amount"] = 100,
				["code"] = 2,
				["type"] = 1,
			},
			{
				["amount"] = 100000,
				["code"] = 9,
				["type"] = 1,
			},
		},
		["Charpter_tips"] = "tipsCD24",
		["pic"] = "fuben_beijing_002.jpg",
		["pic3"] = "fuben_zhangjie_24.png",
	},
}

return Charpter