
local Base = {
	[1] = {
		["quality"] = 6,
		["name"] = "item_1",
		["desc"] = "desc_1",
		["shop_desc"] = "shop_desc_1",
		["introduction"] = "intro_1",
		["source_introduction"] = "from_desc_1",
		["bigPic"] = "gongyong_ziyuanlan_yuanbao.png",
		["smallPic"] = "gongyong_ziyuanlan_yuanbao.png",
	},
	[2] = {
		["quality"] = 6,
		["name"] = "item_2",
		["desc"] = "desc_2",
		["shop_desc"] = "shop_desc_2",
		["introduction"] = "intro_2",
		["source_introduction"] = "from_desc_2",
		["bigPic"] = "gongyong_ziyuanlan_yuanbao.png",
		["smallPic"] = "gongyong_ziyuanlan_yuanbao.png",
	},
	[3] = {
		["quality"] = 6,
		["name"] = "item_3",
		["desc"] = "desc_3",
		["shop_desc"] = "shop_desc_3",
		["introduction"] = "intro_3",
		["source_introduction"] = "from_desc_3",
		["bigPic"] = "gongyong_ziyuanlan_yuanbao.png",
		["smallPic"] = "gongyong_ziyuanlan_yuanbao.png",
	},
	[4] = {
		["quality"] = 6,
		["name"] = "item_4",
		["desc"] = "desc_4",
		["shop_desc"] = "shop_desc_4",
		["introduction"] = "intro_4",
		["source_introduction"] = "from_desc_4",
		["bigPic"] = "gongyong_ziyuanlan_EXP.png",
		["smallPic"] = "gongyong_ziyuanlan_EXP_1.png",
	},
	[5] = {
		["quality"] = 6,
		["name"] = "item_5",
		["desc"] = "desc_5",
		["shop_desc"] = "shop_desc_5",
		["introduction"] = "intro_5",
		["source_introduction"] = "from_desc_5",
		["bigPic"] = "gongyong_ziyuanlan_EXP.png",
		["smallPic"] = "gongyong_ziyuanlan_EXP.png",
	},
	[6] = {
		["quality"] = 6,
		["name"] = "item_6",
		["desc"] = "desc_6",
		["shop_desc"] = "shop_desc_6",
		["introduction"] = "intro_6",
		["source_introduction"] = "from_desc_6",
		["bigPic"] = "gongyong_ziyuanlan_jiangling.png",
		["smallPic"] = "gongyong_ziyuanlan_jiangling.png",
	},
	[7] = {
		["quality"] = 6,
		["name"] = "item_7",
		["desc"] = "desc_7",
		["shop_desc"] = "shop_desc_7",
		["introduction"] = "intro_7",
		["source_introduction"] = "from_desc_7",
		["bigPic"] = "gongyong_ziyuanlan_shengwang.png",
		["smallPic"] = "gongyong_ziyuanlan_shengwang.png",
	},
	[8] = {
		["quality"] = 6,
		["name"] = "item_8",
		["desc"] = "desc_8",
		["shop_desc"] = "shop_desc_8",
		["introduction"] = "intro_8",
		["source_introduction"] = "from_desc_8",
		["bigPic"] = "gongyong_ziyuanlan_gongxun.png",
		["smallPic"] = "gongyong_ziyuanlan_gongxun.png",
	},
	[9] = {
		["quality"] = 6,
		["name"] = "item_9",
		["desc"] = "desc_9",
		["shop_desc"] = "shop_desc_9",
		["introduction"] = "intro_9",
		["source_introduction"] = "from_desc_9",
		["bigPic"] = "gongyong_ziyuanlan_tongqian.png",
		["smallPic"] = "gongyong_ziyuanlan_tongqian.png",
	},
	[10] = {
		["quality"] = 6,
		["name"] = "item_10",
		["desc"] = "desc_10",
		["shop_desc"] = "shop_desc_10",
		["introduction"] = "intro_10",
		["source_introduction"] = "from_desc_10",
		["bigPic"] = "gongyong_ziyuanlan_zhangong.png",
		["smallPic"] = "gongyong_ziyuanlan_zhangong.png",
	},
	[11] = {
		["quality"] = 6,
		["name"] = "item_11",
		["desc"] = "desc_11",
		["shop_desc"] = "shop_desc_11",
		["introduction"] = "intro_11",
		["source_introduction"] = "from_desc_11",
		["bigPic"] = "gongyong_ziyuanlan_jifen.png",
		["smallPic"] = "gongyong_ziyuanlan_jifen.png",
	},
	[12] = {
		["quality"] = 6,
		["name"] = "item_12",
		["desc"] = "desc_12",
		["shop_desc"] = "shop_desc_12",
		["introduction"] = "intro_12",
		["source_introduction"] = "from_desc_12",
		["bigPic"] = "gongyong_ziyuanlan_gongxian.png",
		["smallPic"] = "gongyong_ziyuanlan_gongxian.png",
	},
	[13] = {
		["quality"] = 6,
		["name"] = "item_13",
		["desc"] = "desc_13",
		["shop_desc"] = "shop_desc_13",
		["introduction"] = "intro_13",
		["source_introduction"] = "from_desc_13",
		["bigPic"] = "gongyong_ziyuanlan_tili.png",
		["smallPic"] = "gongyong_ziyuanlan_tili.png",
	},
	[14] = {
		["quality"] = 6,
		["name"] = "item_14",
		["desc"] = "desc_14",
		["shop_desc"] = "shop_desc_14",
		["introduction"] = "intro_14",
		["source_introduction"] = "from_desc_14",
		["bigPic"] = "gongyong_ziyuanlan_xiaofeijifen.png",
		["smallPic"] = "gongyong_ziyuanlan_xiaofeijifen.png",
	},
	[15] = {
		["quality"] = 6,
		["name"] = "item_15",
		["desc"] = "desc_15",
		["shop_desc"] = "shop_desc_15",
		["introduction"] = "intro_15",
		["source_introduction"] = "from_desc_15",
		["bigPic"] = "gongyong_ziyuanlan_jingli.png",
		["smallPic"] = "gongyong_ziyuanlan_jingli.png",
	},
	[16] = {
		["quality"] = 6,
		["name"] = "item_16",
		["desc"] = "desc_16",
		["shop_desc"] = "shop_desc_16",
		["introduction"] = "intro_16",
		["source_introduction"] = "from_desc_16",
		["bigPic"] = "gongyong_ziyuanlan_huoyuedu.png",
		["smallPic"] = "gongyong_ziyuanlan_huoyuedu.png",
	},
	[17] = {
		["quality"] = 6,
		["name"] = "item_17",
		["desc"] = "desc_17",
		["shop_desc"] = "shop_desc_17",
		["introduction"] = "intro_17",
		["source_introduction"] = "from_desc_17",
		["bigPic"] = "gongyong_ziyuanlan_huoyuedu.png",
		["smallPic"] = "gongyong_ziyuanlan_huoyuedu.png",
	},
	[18] = {
		["quality"] = 6,
		["name"] = "item_18",
		["desc"] = "desc_18",
		["shop_desc"] = "shop_desc_18",
		["introduction"] = "intro_18",
		["source_introduction"] = "from_desc_18",
		["bigPic"] = "gongyong_ziyuanlan_huoyuedu.png",
		["smallPic"] = "gongyong_ziyuanlan_huoyuedu.png",
	},
	[19] = {
		["quality"] = 6,
		["name"] = "item_19",
		["desc"] = "desc_19",
		["shop_desc"] = "shop_desc_19",
		["introduction"] = "intro_19",
		["source_introduction"] = "from_desc_19",
		["bigPic"] = "gongyong_ziyuanlan_jingjijifen.png",
		["smallPic"] = "gongyong_ziyuanlan_jingjijifen.png",
	},
	[20] = {
		["quality"] = 6,
		["name"] = "item_20",
		["desc"] = "desc_20",
		["shop_desc"] = "shop_desc_20",
		["introduction"] = "intro_20",
		["source_introduction"] = "from_desc_20",
		["bigPic"] = "gongyong_ziyuanlan_naili.png",
		["smallPic"] = "gongyong_ziyuanlan_naili.png",
	},
}

return Base